name: flame_example
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flame: 0.8.3
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/crate.png
   - assets/images/explosion.png
   - assets/audio/explosion.mp3
   - assets/audio/miss.mp3
   - assets/audio/music.ogg

  fonts:
   - family: Halo
     fonts:
      - asset: assets/fonts/halo.ttf